Repository compsigh/web, pull requests merged in 2025-03, with the labels that each got.

#27 Add `/workingon` Marquee to Community page
  app/api/marquee/route.ts
  app/community/page.tsx
  components/Marquee/Marquee.module.css
  components/Marquee/Marquee.tsx
  components/Marquee/index.ts
  functions/db/index.ts
  functions/db/marquee.ts
  package-lock.json
  package.json
  prisma/migrations/20241123065019_marquee/migration.sql
  prisma/migrations/20241126044121_add_discord_id/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: feature

#28 Upgrade deps
  .eslintrc.json
  app/[...slug]/page.tsx
  app/events/EventList.tsx
  components/Decorations/Soundboard/Soundboard.tsx
  components/Media/Media.tsx
  components/Twinkle/Icon.tsx
  eslint.config.mjs
  next.config.mjs
  next.config.ts
  package-lock.json
  package.json
Labels: dependencies

#29 Enable PPR on `/community`
  app/community/page.tsx
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
Labels: improvement

#31 Handle deleting `<Marquee />` entries
  app/api/marquee/route.ts
  functions/db/marquee.ts
Labels: improvement

#34 Add PPR to `/community`, fr this time
  components/Marquee/Marquee.tsx
Labels: improvement

#26 Add linking to Events cards
  app/[...slug]/page.tsx
  app/events/Event.tsx
  app/events/EventList.tsx
  app/events/Events.module.css
Labels: improvement
